### ISSUE TITLE
Weatherstation2 with ILI9341

### ISSUE THREAD

**Issue by Dancopy** [hellange/arduino#2]
Is it possible to use Weatherstation2 or Weatherstation3 with the normal ILI9341 (No Touch) Display?
What should be changed in the code?
Thanks

**Comment by Dancopy** [comment]
I would love to use 'weatherstation2' or 'weatherstation3' but they are showing many errors. I'm using arduino-1.5.5-r2, as you mention on the site.

- The 'UTouch' library on the site has been replaced by 'URTouch'.
- Adafruit_BMP085 that you make available on the site is not <Adafruit_BMP085_U.h> as in the sketch.

List of errors:

Arduino: 1.5.5-r2 (Windows 8), Placa:"Arduino Uno"

weatherstation2:23: error: 'TFT01_32WD' was not declared in this scope
weatherstation2:24: error: 'UTouch' does not name a type
weatherstation2:26: error: 'Adafruit_BMP085_Unified' does not name a type
weatherstation2.ino: In function 'void setup()':
weatherstation2:36: error: 'myTouch' was not declared in this scope
weatherstation2:37: error: 'PREC_LOW' was not declared in this scope
weatherstation2:43: error: 'RTC' was not declared in this scope
weatherstation2:43: error: 'setSyncProvider' was not declared in this scope
weatherstation2:45: error: 'timeStatus' was not declared in this scope
weatherstation2:45: error: 'timeSet' was not declared in this scope
weatherstation2.ino: At global scope:
weatherstation2:70: error: 'time_t' does not name a type
weatherstation2:71: error: 'time_t' does not name a type
weatherstation2:72: error: 'time_t' does not name a type
weatherstation2.ino: In function 'void renderDisplay()':
weatherstation2:76: error: 'now' was not declared in this scope
weatherstation2:76: error: 'lastMoonPhaseRender' was not declared in this scope
weatherstation2:81: error: 'now' was not declared in this scope
weatherstation2:81: error: 'lastPressureRender' was not declared in this scope
weatherstation2:85: error: 'now' was not declared in this scope
weatherstation2:85: error: 'lastPressureHistoryRender' was not declared in this scope
weatherstation2.ino: In function 'void checkTouch()':
weatherstation2:191: error: 'myTouch' was not declared in this scope
weatherstation2.ino: In function 'void setDateTime()':
weatherstation2:245: error: 'setTime' was not declared in this scope
weatherstation2:246: error: 'RTC' was not declared in this scope
weatherstation2:246: error: 'now' was not declared in this scope
weatherstation2.ino: At global scope:
weatherstation2:277: error: 'TimeChangeRule' does not name a type
weatherstation2:278: error: 'TimeChangeRule' does not name a type
weatherstation2:279: error: 'Timezone' does not name a type
weatherstation2:280: error: 'time_t' does not name a type
weatherstation2.ino: In function 'void showDate(int, int)':
weatherstation2:286: error: 'weekday' was not declared in this scope
weatherstation2:287: error: 'local' was not declared in this scope
weatherstation2:287: error: 'day' was not declared in this scope
weatherstation2:288: error: 'month' was not declared in this scope
weatherstation2:289: error: 'year' was not declared in this scope
weatherstation2.ino: In function 'void showTime(int, int)':
weatherstation2:292: error: 'utc' was not declared in this scope
weatherstation2:292: error: 'now' was not declared in this scope
weatherstation2:293: error: 'TimeChangeRule' was not declared in this scope
weatherstation2:293: error: 'tcr' was not declared in this scope
weatherstation2:294: error: 'local' was not declared in this scope
weatherstation2:294: error: 'myTZ' was not declared in this scope
weatherstation2:302: error: 'hour' was not declared in this scope
weatherstation2:303: error: 'minute' was not declared in this scope
weatherstation2:306: error: 'second' was not declared in this scope
weatherstation2.ino: In function 'void showMoonPhase(int, int)':
weatherstation2:314: error: 'year' was not declared in this scope
weatherstation2:314: error: 'month' was not declared in this scope
weatherstation2:314: error: 'now' was not declared in this scope
weatherstation2:314: error: 'day' was not declared in this scope
weatherstation2.ino: In function 'void showMoonPhaseWeek(int, int)':
weatherstation2:323: error: 'time_t' was not declared in this scope
weatherstation2:323: error: expected `;' before 'oneDay'
weatherstation2:328: error: expected `;' before 'time'
weatherstation2:329: error: 'time' was not declared in this scope
weatherstation2:329: error: 'year' was not declared in this scope
weatherstation2:329: error: 'month' was not declared in this scope
weatherstation2:329: error: 'day' was not declared in this scope
weatherstation2.ino: In function 'void displaySensorDetails()':
weatherstation2:348: error: 'sensor_t' was not declared in this scope
weatherstation2:348: error: expected `;' before 'sensor'
weatherstation2:349: error: 'bmp' was not declared in this scope
weatherstation2:349: error: 'sensor' was not declared in this scope
weatherstation2.ino: In function 'void showPressure()':
weatherstation2:364: error: 'bmp' was not declared in this scope
weatherstation2.ino: In function 'float getMbar()':
weatherstation2:382: error: 'sensors_event_t' was not declared in this scope
weatherstation2:382: error: expected `;' before 'event'
weatherstation2:383: error: 'bmp' was not declared in this scope
weatherstation2:383: error: 'event' was not declared in this scope
weatherstation2.ino: In function 'void showTemperature()':
weatherstation2:394: error: 'bmp' was not declared in this scope

If you can help me, thank you very much,

Daniel Fernandes

**Comment by hellange** [comment]
I also get a lot of errors when trying to compile with 1.8.5. Don't have older versions of the IDE. This weatherstation2 project is no longer being maintained, so it will probably not be updated/fixed by me in near future.
You could try to remove some of the .cpp and .h files and include the ones in the corresponding directories. You probably also have to find a more up-to-date version of the DS1307RTC code.

**Comment by Dancopy** [comment]
I did what you said but it did not work; It's a shame, but I'll leave this project aside. If, by chance you update it, please send me by my email? (meuviolino@hotmail.com) Thanks

**Comment by Dancopy** [comment]
Greetings! First, a word of sincerity:
I much prefer your "weatherstation3" project, although its simplicity, but the presentation of the screen (icons and numbers) was very beautiful; It would be nice to do so with an esp8266 and a larger display, as in a 3.5" ILI9488 with the same design.

I was able to do it with a 3.2" ILI9341 SPI Breakout Touch Display but, I can't CALIBRATE the touch screen; it reaches the INSTRUCTIONS portion of the screen and then no longer proceeds, the screen does not respond to the pen touch (may be defective).  I am considering buying the display you use: 400x240

I am using weatherstation3 sketch with Arduino Mega 2560 Pro; I connected a BMP180-GY68 sensor but it is showing on the screen: Could not find a valid BMP085 pressure sensor.
I connected the sensor to pins 20 and 21 (SDA and SCL) on the Mega.  Any tips?

PS. I haven't connected the DS3231 RTC yet!

Thank you
